import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { config } from 'dotenv';
import { sql } from 'drizzle-orm';
import { createDb } from '../src/client.js';
import {
	artists,
	artistsToTracks,
	tokens,
	tracks,
	userLikedArtists,
	userLikedTracks,
	users,
} from '../src/schema/index.js';

config();

const db = createDb(process.env.DATABASE_URL);
const packageRoot = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const dumpPath = path.join(packageRoot, 'dumps/data.sql');
const schemaPath = path.join(packageRoot, 'drizzle/0000_lowly_mentallo.sql');

function sqlLiteral(value: unknown): string {
	if (value === null || value === undefined) {
		return 'NULL';
	}

	if (typeof value === 'number') {
		if (!Number.isFinite(value)) {
			throw new Error(`Cannot dump non-finite number: ${value}`);
		}
		return String(value);
	}

	if (typeof value === 'boolean') {
		return value ? 'TRUE' : 'FALSE';
	}

	if (value instanceof Date) {
		return `'${value.toISOString()}'`;
	}

	if (typeof value === 'string') {
		return `'${value.replaceAll("'", "''")}'`;
	}

	throw new Error(`Unsupported dump value type: ${typeof value}`);
}

function insertRows(
	table: string,
	columns: string[],
	rows: Array<Record<string, unknown>>,
): string {
	if (rows.length === 0) {
		return `-- ${table}: 0 rows\n`;
	}

	const values = rows
		.map(
			(row) =>
				`  (${columns.map((column) => sqlLiteral(row[column])).join(', ')})`,
		)
		.join(',\n');

	return (
		`INSERT INTO public.${table} (${columns.join(', ')}) VALUES\n` +
		`${values};\n`
	);
}

async function main() {
	const [
		artistRows,
		trackRows,
		userRows,
		linkRows,
		tokenRows,
		likedArtistRows,
		likedTrackRows,
	] = await Promise.all([
		db.select().from(artists).orderBy(artists.id),
		db.select().from(tracks).orderBy(tracks.id),
		db.select().from(users).orderBy(users.id),
		db.select().from(artistsToTracks).orderBy(artistsToTracks.artistId),
		db.select().from(tokens).orderBy(tokens.key),
		db.select().from(userLikedArtists).orderBy(userLikedArtists.userId),
		db.select().from(userLikedTracks).orderBy(userLikedTracks.userId),
	]);

	const schemaSql = (await readFile(schemaPath, 'utf8'))
		.replaceAll('--> statement-breakpoint', '')
		.trim();

	let drizzleMigrationsSql = '';
	try {
		const migrations = await db.execute<{
			id: number;
			hash: string;
			created_at: string | number | null;
		}>(sql`SELECT id, hash, created_at FROM drizzle.__drizzle_migrations ORDER BY id`);

		if (migrations.rows.length > 0) {
			const values = migrations.rows
				.map(
					(row) =>
						`  (${sqlLiteral(row.id)}, ${sqlLiteral(row.hash)}, ${sqlLiteral(row.created_at)})`,
				)
				.join(',\n');

			drizzleMigrationsSql = `
CREATE SCHEMA IF NOT EXISTS drizzle;

CREATE TABLE drizzle.__drizzle_migrations (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	hash text NOT NULL,
	created_at bigint
);

INSERT INTO drizzle.__drizzle_migrations (id, hash, created_at) VALUES
${values};

SELECT setval(
	'drizzle.__drizzle_migrations_id_seq',
	COALESCE((SELECT MAX(id) FROM drizzle.__drizzle_migrations), 1),
	(SELECT COUNT(*) FROM drizzle.__drizzle_migrations) > 0
);
`;
		}
	} catch {
		drizzleMigrationsSql = '';
	}

	const dumpSql = `-- Full dump for a completely empty PostgreSQL database.
-- Run this file as-is. Do not run drizzle migrate first.

BEGIN;

${schemaSql}
${drizzleMigrationsSql}
${insertRows(
	'artists',
	['id', 'name', 'artist_img', 'big_img', 'likes'],
	artistRows.map((row) => ({
		id: row.id,
		name: row.name,
		artist_img: row.artistImg,
		big_img: row.bigImg,
		likes: row.likes,
	})),
)}
${insertRows(
	'tracks',
	['id', 'title', 'album_img', 'music', 'auditions'],
	trackRows.map((row) => ({
		id: row.id,
		title: row.title,
		album_img: row.albumImg,
		music: row.music,
		auditions: row.auditions,
	})),
)}
${insertRows(
	'users',
	['id', 'username', 'email', 'password_hash', 'reg_date', 'user_img'],
	userRows.map((row) => ({
		id: row.id,
		username: row.username,
		email: row.email,
		password_hash: row.passwordHash,
		reg_date: row.regDate,
		user_img: row.userImg,
	})),
)}
${insertRows(
	'artists_to_tracks',
	['artist_id', 'track_id'],
	linkRows.map((row) => ({
		artist_id: row.artistId,
		track_id: row.trackId,
	})),
)}
${insertRows(
	'tokens',
	['key', 'user_id', 'created_at'],
	tokenRows.map((row) => ({
		key: row.key,
		user_id: row.userId,
		created_at: row.createdAt,
	})),
)}
${insertRows(
	'user_liked_artists',
	['user_id', 'artist_id', 'created_at'],
	likedArtistRows.map((row) => ({
		user_id: row.userId,
		artist_id: row.artistId,
		created_at: row.createdAt,
	})),
)}
${insertRows(
	'user_liked_tracks',
	['user_id', 'track_id', 'created_at'],
	likedTrackRows.map((row) => ({
		user_id: row.userId,
		track_id: row.trackId,
		created_at: row.createdAt,
	})),
)}
SELECT setval(
	'public.artists_id_seq',
	COALESCE((SELECT MAX(id) FROM public.artists), 1),
	(SELECT COUNT(*) FROM public.artists) > 0
);

COMMIT;
`;

	await mkdir(path.dirname(dumpPath), { recursive: true });
	await writeFile(dumpPath, dumpSql, 'utf8');

	console.log(
		`Dumped ${artistRows.length} artists, ${trackRows.length} tracks, ${linkRows.length} links, ${userRows.length} users, ${tokenRows.length} tokens, ${likedArtistRows.length} liked artists, ${likedTrackRows.length} liked tracks`,
	);
	console.log(`Wrote ${path.relative(process.cwd(), dumpPath)}`);
	process.exit(0);
}

main().catch((error) => {
	console.error(error);
	process.exit(1);
});
