/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArtistNameRouteImport } from './routes/artist/$name'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeFullscreenRouteImport } from './routes/home/fullscreen'
import { Route as HomeLikedRouteImport } from './routes/home/liked'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistNameRoute = ArtistNameRouteImport.update({
  id: '/artist/$name',
  path: '/artist/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeFullscreenRoute = HomeFullscreenRouteImport.update({
  id: '/home/fullscreen',
  path: '/home/fullscreen',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLikedRoute = HomeLikedRouteImport.update({
  id: '/home/liked',
  path: '/home/liked',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/artist/$name': typeof ArtistNameRoute
  '/home/fullscreen': typeof HomeFullscreenRoute
  '/home/liked': typeof HomeLikedRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/artist/$name': typeof ArtistNameRoute
  '/home/fullscreen': typeof HomeFullscreenRoute
  '/home/liked': typeof HomeLikedRoute
  '/home': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/artist/$name': typeof ArtistNameRoute
  '/home/fullscreen': typeof HomeFullscreenRoute
  '/home/liked': typeof HomeLikedRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/artist/$name'
    | '/home/fullscreen'
    | '/home/liked'
    | '/home/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/artist/$name'
    | '/home/fullscreen'
    | '/home/liked'
    | '/home'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/artist/$name'
    | '/home/fullscreen'
    | '/home/liked'
    | '/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ArtistNameRoute: typeof ArtistNameRoute
  HomeFullscreenRoute: typeof HomeFullscreenRoute
  HomeLikedRoute: typeof HomeLikedRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$name': {
      id: '/artist/$name'
      path: '/artist/$name'
      fullPath: '/artist/$name'
      preLoaderRoute: typeof ArtistNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/fullscreen': {
      id: '/home/fullscreen'
      path: '/home/fullscreen'
      fullPath: '/home/fullscreen'
      preLoaderRoute: typeof HomeFullscreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/liked': {
      id: '/home/liked'
      path: '/home/liked'
      fullPath: '/home/liked'
      preLoaderRoute: typeof HomeLikedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ArtistNameRoute: ArtistNameRoute,
  HomeFullscreenRoute: HomeFullscreenRoute,
  HomeLikedRoute: HomeLikedRoute,
  HomeIndexRoute: HomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
